### ISSUE TITLE
vbscan doesn't start on kali linux rooling

### ISSUE THREAD

**Issue by ChamsBouzaiene** [rezasp/vbscan#13]
i cloned the project to kali using
git clone
then went to the directory passed this command
perl vbscan.pl
and nothing happens 
:( what should i do help ?

**Comment by rezasp** [comment]
I check vbscan on "Linux 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux" and its executed with out any bug or problem
![screen shot 2016-10-18 at 3 33 31 am](https://cloud.githubusercontent.com/assets/12808790/19459919/af263756-94e3-11e6-9d6b-393d2ff8907c.jpg)

Please give me information about your problem (OS , kernel , error , screenshot , etc)

Thank you.

**Comment by ChamsBouzaiene** [comment]
Ok so this is a screenshot of the problem when i execute perl vbscan.pl nothing appears on the terminal 

![screenshot from 2016-10-18 10-57-15](https://cloud.githubusercontent.com/assets/22895649/19483393/2c264348-9522-11e6-9863-e9ac2cfb5660.png)

**Comment by Indeserpen** [comment]
I can confirm this error, earlier version was working perfectly! It just does nothing!!

his is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
(with 60 registered patches, see perl -V for more detail)

Copyright 1987-2016, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

root@kali:~# uname -a\

> Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.5-1kali3 (2016-09-29) x86_64 GNU/Linux

**Comment by rezasp** [comment]
Check your terminal configuration, i checked it on (Latest version of kali , Ubuntu , OS X , tail , Windows 10 bash , CentOS) and there is no problem

can you check it on other OS ?

![photo_2016-10-19_00-29-35](https://cloud.githubusercontent.com/assets/12808790/19496253/9057648e-9593-11e6-820d-363c37f0252f.jpg)
![screen shot 2016-10-19 at 12 15 19 am](https://cloud.githubusercontent.com/assets/12808790/19496260/94a69d02-9593-11e6-8d80-11eb418d00d7.jpg)
![screen shot 2016-10-18 at 10 59 39 pm](https://cloud.githubusercontent.com/assets/12808790/19496263/98f626ac-9593-11e6-8b9c-a7349ac99710.jpg)

**Comment by rezasp** [comment]
We saw this problem in latest version of perl, issue reported but still no fix out there, downgrade your perl version to "perl 5, version 22, subversion 2 (v5.22.2)" and should be work
- Don't upgrade your perl version to latest

**Comment by rezasp** [comment]
Bug fixed , check latest version @alchemist107 @jteslaxxx

**Comment by Indeserpen** [comment]
All good for me, Thanks!
