### ISSUE TITLE
Needs proper output flag instead of redirection

### ISSUE THREAD

**Issue by vxbinaca** [rezasp/vbscan#4]
See title. Color information is messing up output redirected 'log files'.

 Nice work! Very interesting script. I hope you'll keep this up to date.

**Comment by rezasp** [comment]
Can u explain more about this issue

**Comment by vxbinaca** [comment]
[+] Checking for html tags status
[31m[++] html tag is Disable :(
[34m
[+] Checking c99 xml shell in admincp/subscriptions.php
[31m[++] c99 xml shell is Not Found:(
[34m

Term::ANSIcolor is spitting color codes ("[31m" etc etc) into the report file. Piping it through "strings" alleviates some of the problem (ASCII color codes and anything not human readable) but I'm still left with that stuff in there. It renders nice in terminal, but when I go to read it in `nano` or `gedit` i run into it,

**Comment by rezasp** [comment]
Thanks for report
i will add standard report in new version.
