### ISSUE TITLE
Unable to run on ubuntu

### ISSUE THREAD

**Issue by kedramon** [rezasp/vbscan#9]
After running on ubuntu perl vbscan.pl (link|path)

String found where operator expected at modules/cpfinder.pl line 8, near "fprint "admincp does not exist or renamed""
    (Do you need to predeclare fprint?)

Undefined subroutine &main::tprint called at vbscan.pl line 76.
perl v5.14.2

**Comment by rezasp** [comment]
Fixed ;)
use new version , test it , enjoy

**Comment by kedramon** [comment]
Hi,
still some bug
Undefined subroutine &main::tprint called at vbscan.pl line 76.

**Comment by rezasp** [comment]
Do you use vbscan 0.1.5 ?

**Comment by rezasp** [comment]
[vbtest.zip](https://github.com/rezasp/vbscan/files/123895/vbtest.zip)

Please test it , and give me your result !

**Comment by kedramon** [comment]
Hi, 
Yes, I tried 0.1.5,
vbtest produce empty report file

~/vbtest$ perl vbscan.pl /home/***/www/forum/
Your Report : reports/.txt

**Comment by rezasp** [comment]
check new relaese

**Comment by kedramon** [comment]
Same behavior.

**Comment by Laggii** [comment]
Well, there is a small change which I did in pull request for the version before. See https://github.com/Laggii/vbscan/commit/3b2960956cb845262bbe6a9144590f5ff482680c

Update your own files or use my fork.
Pull request created

**Comment by rezasp** [comment]
Thanks to Laggii
issue fixed
check it
